/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperadorIndexRouteImport } from './routes/operador.index'
import { Route as ManutencaoIndexRouteImport } from './routes/manutencao.index'
import { Route as GestaoIndexRouteImport } from './routes/gestao.index'
import { Route as OperadorVersoRouteImport } from './routes/operador.verso'
import { Route as OperadorResumoRouteImport } from './routes/operador.resumo'
import { Route as OperadorMomentoRouteImport } from './routes/operador.momento'
import { Route as OperadorItRouteImport } from './routes/operador.it'
import { Route as OperadorHistoricoRouteImport } from './routes/operador.historico'
import { Route as OperadorContextoRouteImport } from './routes/operador.contexto'
import { Route as OperadorConfirmacaoRouteImport } from './routes/operador.confirmacao'
import { Route as OperadorChecklistRouteImport } from './routes/operador.checklist'
import { Route as ManutencaoFiltrosRouteImport } from './routes/manutencao.filtros'
import { Route as ManutencaoAnomaliasRouteImport } from './routes/manutencao.anomalias'
import { Route as GestaoRelatorioRouteImport } from './routes/gestao.relatorio'
import { Route as GestaoItTreinamentosRouteImport } from './routes/gestao.it-treinamentos'
import { Route as GestaoItAnalyticsRouteImport } from './routes/gestao.it-analytics'
import { Route as GestaoFiltrosRouteImport } from './routes/gestao.filtros'
import { Route as GestaoChecklistsRouteImport } from './routes/gestao.checklists'
import { Route as GestaoAnomaliasRouteImport } from './routes/gestao.anomalias'
import { Route as OperadorVersoPtpRouteImport } from './routes/operador.verso.ptp'
import { Route as OperadorVersoLimpezaRouteImport } from './routes/operador.verso.limpeza'
import { Route as OperadorItAtaRouteImport } from './routes/operador.it.ata'
import { Route as OperadorItDocRouteImport } from './routes/operador.it.$doc'
import { Route as OperadorAnomaliaNovaRouteImport } from './routes/operador.anomalia.nova'
import { Route as ManutencaoAnomaliaNovaRouteImport } from './routes/manutencao.anomalia.nova'
import { Route as OperadorVisualizarChecklistIdRouteImport } from './routes/operador.visualizar.checklist.$id'
import { Route as OperadorVisualizarAnomaliaIdRouteImport } from './routes/operador.visualizar.anomalia.$id'
import { Route as OperadorVersoPtpJanelaCodigoRouteImport } from './routes/operador.verso.ptp.$janelaCodigo'
import { Route as ManutencaoVisualizarAnomaliaIdRouteImport } from './routes/manutencao.visualizar.anomalia.$id'
import { Route as GestaoVisualizarDiaFolhaKeyRouteImport } from './routes/gestao.visualizar.dia.$folhaKey'
import { Route as GestaoVisualizarChecklistIdRouteImport } from './routes/gestao.visualizar.checklist.$id'
import { Route as GestaoVisualizarAnomaliaIdRouteImport } from './routes/gestao.visualizar.anomalia.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorIndexRoute = OperadorIndexRouteImport.update({
  id: '/operador/',
  path: '/operador/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoIndexRoute = ManutencaoIndexRouteImport.update({
  id: '/manutencao/',
  path: '/manutencao/',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoIndexRoute = GestaoIndexRouteImport.update({
  id: '/gestao/',
  path: '/gestao/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorVersoRoute = OperadorVersoRouteImport.update({
  id: '/operador/verso',
  path: '/operador/verso',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorResumoRoute = OperadorResumoRouteImport.update({
  id: '/operador/resumo',
  path: '/operador/resumo',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorMomentoRoute = OperadorMomentoRouteImport.update({
  id: '/operador/momento',
  path: '/operador/momento',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorItRoute = OperadorItRouteImport.update({
  id: '/operador/it',
  path: '/operador/it',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorHistoricoRoute = OperadorHistoricoRouteImport.update({
  id: '/operador/historico',
  path: '/operador/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorContextoRoute = OperadorContextoRouteImport.update({
  id: '/operador/contexto',
  path: '/operador/contexto',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorConfirmacaoRoute = OperadorConfirmacaoRouteImport.update({
  id: '/operador/confirmacao',
  path: '/operador/confirmacao',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorChecklistRoute = OperadorChecklistRouteImport.update({
  id: '/operador/checklist',
  path: '/operador/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoFiltrosRoute = ManutencaoFiltrosRouteImport.update({
  id: '/manutencao/filtros',
  path: '/manutencao/filtros',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoAnomaliasRoute = ManutencaoAnomaliasRouteImport.update({
  id: '/manutencao/anomalias',
  path: '/manutencao/anomalias',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRelatorioRoute = GestaoRelatorioRouteImport.update({
  id: '/gestao/relatorio',
  path: '/gestao/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoItTreinamentosRoute = GestaoItTreinamentosRouteImport.update({
  id: '/gestao/it-treinamentos',
  path: '/gestao/it-treinamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoItAnalyticsRoute = GestaoItAnalyticsRouteImport.update({
  id: '/gestao/it-analytics',
  path: '/gestao/it-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoFiltrosRoute = GestaoFiltrosRouteImport.update({
  id: '/gestao/filtros',
  path: '/gestao/filtros',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoChecklistsRoute = GestaoChecklistsRouteImport.update({
  id: '/gestao/checklists',
  path: '/gestao/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoAnomaliasRoute = GestaoAnomaliasRouteImport.update({
  id: '/gestao/anomalias',
  path: '/gestao/anomalias',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorVersoPtpRoute = OperadorVersoPtpRouteImport.update({
  id: '/ptp',
  path: '/ptp',
  getParentRoute: () => OperadorVersoRoute,
} as any)
const OperadorVersoLimpezaRoute = OperadorVersoLimpezaRouteImport.update({
  id: '/limpeza',
  path: '/limpeza',
  getParentRoute: () => OperadorVersoRoute,
} as any)
const OperadorItAtaRoute = OperadorItAtaRouteImport.update({
  id: '/ata',
  path: '/ata',
  getParentRoute: () => OperadorItRoute,
} as any)
const OperadorItDocRoute = OperadorItDocRouteImport.update({
  id: '/$doc',
  path: '/$doc',
  getParentRoute: () => OperadorItRoute,
} as any)
const OperadorAnomaliaNovaRoute = OperadorAnomaliaNovaRouteImport.update({
  id: '/operador/anomalia/nova',
  path: '/operador/anomalia/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoAnomaliaNovaRoute = ManutencaoAnomaliaNovaRouteImport.update({
  id: '/manutencao/anomalia/nova',
  path: '/manutencao/anomalia/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorVisualizarChecklistIdRoute =
  OperadorVisualizarChecklistIdRouteImport.update({
    id: '/operador/visualizar/checklist/$id',
    path: '/operador/visualizar/checklist/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperadorVisualizarAnomaliaIdRoute =
  OperadorVisualizarAnomaliaIdRouteImport.update({
    id: '/operador/visualizar/anomalia/$id',
    path: '/operador/visualizar/anomalia/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperadorVersoPtpJanelaCodigoRoute =
  OperadorVersoPtpJanelaCodigoRouteImport.update({
    id: '/$janelaCodigo',
    path: '/$janelaCodigo',
    getParentRoute: () => OperadorVersoPtpRoute,
  } as any)
const ManutencaoVisualizarAnomaliaIdRoute =
  ManutencaoVisualizarAnomaliaIdRouteImport.update({
    id: '/manutencao/visualizar/anomalia/$id',
    path: '/manutencao/visualizar/anomalia/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const GestaoVisualizarDiaFolhaKeyRoute =
  GestaoVisualizarDiaFolhaKeyRouteImport.update({
    id: '/gestao/visualizar/dia/$folhaKey',
    path: '/gestao/visualizar/dia/$folhaKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const GestaoVisualizarChecklistIdRoute =
  GestaoVisualizarChecklistIdRouteImport.update({
    id: '/gestao/visualizar/checklist/$id',
    path: '/gestao/visualizar/checklist/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const GestaoVisualizarAnomaliaIdRoute =
  GestaoVisualizarAnomaliaIdRouteImport.update({
    id: '/gestao/visualizar/anomalia/$id',
    path: '/gestao/visualizar/anomalia/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gestao/anomalias': typeof GestaoAnomaliasRoute
  '/gestao/checklists': typeof GestaoChecklistsRoute
  '/gestao/filtros': typeof GestaoFiltrosRoute
  '/gestao/it-analytics': typeof GestaoItAnalyticsRoute
  '/gestao/it-treinamentos': typeof GestaoItTreinamentosRoute
  '/gestao/relatorio': typeof GestaoRelatorioRoute
  '/manutencao/anomalias': typeof ManutencaoAnomaliasRoute
  '/manutencao/filtros': typeof ManutencaoFiltrosRoute
  '/operador/checklist': typeof OperadorChecklistRoute
  '/operador/confirmacao': typeof OperadorConfirmacaoRoute
  '/operador/contexto': typeof OperadorContextoRoute
  '/operador/historico': typeof OperadorHistoricoRoute
  '/operador/it': typeof OperadorItRouteWithChildren
  '/operador/momento': typeof OperadorMomentoRoute
  '/operador/resumo': typeof OperadorResumoRoute
  '/operador/verso': typeof OperadorVersoRouteWithChildren
  '/gestao/': typeof GestaoIndexRoute
  '/manutencao/': typeof ManutencaoIndexRoute
  '/operador/': typeof OperadorIndexRoute
  '/manutencao/anomalia/nova': typeof ManutencaoAnomaliaNovaRoute
  '/operador/anomalia/nova': typeof OperadorAnomaliaNovaRoute
  '/operador/it/$doc': typeof OperadorItDocRoute
  '/operador/it/ata': typeof OperadorItAtaRoute
  '/operador/verso/limpeza': typeof OperadorVersoLimpezaRoute
  '/operador/verso/ptp': typeof OperadorVersoPtpRouteWithChildren
  '/gestao/visualizar/anomalia/$id': typeof GestaoVisualizarAnomaliaIdRoute
  '/gestao/visualizar/checklist/$id': typeof GestaoVisualizarChecklistIdRoute
  '/gestao/visualizar/dia/$folhaKey': typeof GestaoVisualizarDiaFolhaKeyRoute
  '/manutencao/visualizar/anomalia/$id': typeof ManutencaoVisualizarAnomaliaIdRoute
  '/operador/verso/ptp/$janelaCodigo': typeof OperadorVersoPtpJanelaCodigoRoute
  '/operador/visualizar/anomalia/$id': typeof OperadorVisualizarAnomaliaIdRoute
  '/operador/visualizar/checklist/$id': typeof OperadorVisualizarChecklistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gestao/anomalias': typeof GestaoAnomaliasRoute
  '/gestao/checklists': typeof GestaoChecklistsRoute
  '/gestao/filtros': typeof GestaoFiltrosRoute
  '/gestao/it-analytics': typeof GestaoItAnalyticsRoute
  '/gestao/it-treinamentos': typeof GestaoItTreinamentosRoute
  '/gestao/relatorio': typeof GestaoRelatorioRoute
  '/manutencao/anomalias': typeof ManutencaoAnomaliasRoute
  '/manutencao/filtros': typeof ManutencaoFiltrosRoute
  '/operador/checklist': typeof OperadorChecklistRoute
  '/operador/confirmacao': typeof OperadorConfirmacaoRoute
  '/operador/contexto': typeof OperadorContextoRoute
  '/operador/historico': typeof OperadorHistoricoRoute
  '/operador/it': typeof OperadorItRouteWithChildren
  '/operador/momento': typeof OperadorMomentoRoute
  '/operador/resumo': typeof OperadorResumoRoute
  '/operador/verso': typeof OperadorVersoRouteWithChildren
  '/gestao': typeof GestaoIndexRoute
  '/manutencao': typeof ManutencaoIndexRoute
  '/operador': typeof OperadorIndexRoute
  '/manutencao/anomalia/nova': typeof ManutencaoAnomaliaNovaRoute
  '/operador/anomalia/nova': typeof OperadorAnomaliaNovaRoute
  '/operador/it/$doc': typeof OperadorItDocRoute
  '/operador/it/ata': typeof OperadorItAtaRoute
  '/operador/verso/limpeza': typeof OperadorVersoLimpezaRoute
  '/operador/verso/ptp': typeof OperadorVersoPtpRouteWithChildren
  '/gestao/visualizar/anomalia/$id': typeof GestaoVisualizarAnomaliaIdRoute
  '/gestao/visualizar/checklist/$id': typeof GestaoVisualizarChecklistIdRoute
  '/gestao/visualizar/dia/$folhaKey': typeof GestaoVisualizarDiaFolhaKeyRoute
  '/manutencao/visualizar/anomalia/$id': typeof ManutencaoVisualizarAnomaliaIdRoute
  '/operador/verso/ptp/$janelaCodigo': typeof OperadorVersoPtpJanelaCodigoRoute
  '/operador/visualizar/anomalia/$id': typeof OperadorVisualizarAnomaliaIdRoute
  '/operador/visualizar/checklist/$id': typeof OperadorVisualizarChecklistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gestao/anomalias': typeof GestaoAnomaliasRoute
  '/gestao/checklists': typeof GestaoChecklistsRoute
  '/gestao/filtros': typeof GestaoFiltrosRoute
  '/gestao/it-analytics': typeof GestaoItAnalyticsRoute
  '/gestao/it-treinamentos': typeof GestaoItTreinamentosRoute
  '/gestao/relatorio': typeof GestaoRelatorioRoute
  '/manutencao/anomalias': typeof ManutencaoAnomaliasRoute
  '/manutencao/filtros': typeof ManutencaoFiltrosRoute
  '/operador/checklist': typeof OperadorChecklistRoute
  '/operador/confirmacao': typeof OperadorConfirmacaoRoute
  '/operador/contexto': typeof OperadorContextoRoute
  '/operador/historico': typeof OperadorHistoricoRoute
  '/operador/it': typeof OperadorItRouteWithChildren
  '/operador/momento': typeof OperadorMomentoRoute
  '/operador/resumo': typeof OperadorResumoRoute
  '/operador/verso': typeof OperadorVersoRouteWithChildren
  '/gestao/': typeof GestaoIndexRoute
  '/manutencao/': typeof ManutencaoIndexRoute
  '/operador/': typeof OperadorIndexRoute
  '/manutencao/anomalia/nova': typeof ManutencaoAnomaliaNovaRoute
  '/operador/anomalia/nova': typeof OperadorAnomaliaNovaRoute
  '/operador/it/$doc': typeof OperadorItDocRoute
  '/operador/it/ata': typeof OperadorItAtaRoute
  '/operador/verso/limpeza': typeof OperadorVersoLimpezaRoute
  '/operador/verso/ptp': typeof OperadorVersoPtpRouteWithChildren
  '/gestao/visualizar/anomalia/$id': typeof GestaoVisualizarAnomaliaIdRoute
  '/gestao/visualizar/checklist/$id': typeof GestaoVisualizarChecklistIdRoute
  '/gestao/visualizar/dia/$folhaKey': typeof GestaoVisualizarDiaFolhaKeyRoute
  '/manutencao/visualizar/anomalia/$id': typeof ManutencaoVisualizarAnomaliaIdRoute
  '/operador/verso/ptp/$janelaCodigo': typeof OperadorVersoPtpJanelaCodigoRoute
  '/operador/visualizar/anomalia/$id': typeof OperadorVisualizarAnomaliaIdRoute
  '/operador/visualizar/checklist/$id': typeof OperadorVisualizarChecklistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gestao/anomalias'
    | '/gestao/checklists'
    | '/gestao/filtros'
    | '/gestao/it-analytics'
    | '/gestao/it-treinamentos'
    | '/gestao/relatorio'
    | '/manutencao/anomalias'
    | '/manutencao/filtros'
    | '/operador/checklist'
    | '/operador/confirmacao'
    | '/operador/contexto'
    | '/operador/historico'
    | '/operador/it'
    | '/operador/momento'
    | '/operador/resumo'
    | '/operador/verso'
    | '/gestao/'
    | '/manutencao/'
    | '/operador/'
    | '/manutencao/anomalia/nova'
    | '/operador/anomalia/nova'
    | '/operador/it/$doc'
    | '/operador/it/ata'
    | '/operador/verso/limpeza'
    | '/operador/verso/ptp'
    | '/gestao/visualizar/anomalia/$id'
    | '/gestao/visualizar/checklist/$id'
    | '/gestao/visualizar/dia/$folhaKey'
    | '/manutencao/visualizar/anomalia/$id'
    | '/operador/verso/ptp/$janelaCodigo'
    | '/operador/visualizar/anomalia/$id'
    | '/operador/visualizar/checklist/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gestao/anomalias'
    | '/gestao/checklists'
    | '/gestao/filtros'
    | '/gestao/it-analytics'
    | '/gestao/it-treinamentos'
    | '/gestao/relatorio'
    | '/manutencao/anomalias'
    | '/manutencao/filtros'
    | '/operador/checklist'
    | '/operador/confirmacao'
    | '/operador/contexto'
    | '/operador/historico'
    | '/operador/it'
    | '/operador/momento'
    | '/operador/resumo'
    | '/operador/verso'
    | '/gestao'
    | '/manutencao'
    | '/operador'
    | '/manutencao/anomalia/nova'
    | '/operador/anomalia/nova'
    | '/operador/it/$doc'
    | '/operador/it/ata'
    | '/operador/verso/limpeza'
    | '/operador/verso/ptp'
    | '/gestao/visualizar/anomalia/$id'
    | '/gestao/visualizar/checklist/$id'
    | '/gestao/visualizar/dia/$folhaKey'
    | '/manutencao/visualizar/anomalia/$id'
    | '/operador/verso/ptp/$janelaCodigo'
    | '/operador/visualizar/anomalia/$id'
    | '/operador/visualizar/checklist/$id'
  id:
    | '__root__'
    | '/'
    | '/gestao/anomalias'
    | '/gestao/checklists'
    | '/gestao/filtros'
    | '/gestao/it-analytics'
    | '/gestao/it-treinamentos'
    | '/gestao/relatorio'
    | '/manutencao/anomalias'
    | '/manutencao/filtros'
    | '/operador/checklist'
    | '/operador/confirmacao'
    | '/operador/contexto'
    | '/operador/historico'
    | '/operador/it'
    | '/operador/momento'
    | '/operador/resumo'
    | '/operador/verso'
    | '/gestao/'
    | '/manutencao/'
    | '/operador/'
    | '/manutencao/anomalia/nova'
    | '/operador/anomalia/nova'
    | '/operador/it/$doc'
    | '/operador/it/ata'
    | '/operador/verso/limpeza'
    | '/operador/verso/ptp'
    | '/gestao/visualizar/anomalia/$id'
    | '/gestao/visualizar/checklist/$id'
    | '/gestao/visualizar/dia/$folhaKey'
    | '/manutencao/visualizar/anomalia/$id'
    | '/operador/verso/ptp/$janelaCodigo'
    | '/operador/visualizar/anomalia/$id'
    | '/operador/visualizar/checklist/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GestaoAnomaliasRoute: typeof GestaoAnomaliasRoute
  GestaoChecklistsRoute: typeof GestaoChecklistsRoute
  GestaoFiltrosRoute: typeof GestaoFiltrosRoute
  GestaoItAnalyticsRoute: typeof GestaoItAnalyticsRoute
  GestaoItTreinamentosRoute: typeof GestaoItTreinamentosRoute
  GestaoRelatorioRoute: typeof GestaoRelatorioRoute
  ManutencaoAnomaliasRoute: typeof ManutencaoAnomaliasRoute
  ManutencaoFiltrosRoute: typeof ManutencaoFiltrosRoute
  OperadorChecklistRoute: typeof OperadorChecklistRoute
  OperadorConfirmacaoRoute: typeof OperadorConfirmacaoRoute
  OperadorContextoRoute: typeof OperadorContextoRoute
  OperadorHistoricoRoute: typeof OperadorHistoricoRoute
  OperadorItRoute: typeof OperadorItRouteWithChildren
  OperadorMomentoRoute: typeof OperadorMomentoRoute
  OperadorResumoRoute: typeof OperadorResumoRoute
  OperadorVersoRoute: typeof OperadorVersoRouteWithChildren
  GestaoIndexRoute: typeof GestaoIndexRoute
  ManutencaoIndexRoute: typeof ManutencaoIndexRoute
  OperadorIndexRoute: typeof OperadorIndexRoute
  ManutencaoAnomaliaNovaRoute: typeof ManutencaoAnomaliaNovaRoute
  OperadorAnomaliaNovaRoute: typeof OperadorAnomaliaNovaRoute
  GestaoVisualizarAnomaliaIdRoute: typeof GestaoVisualizarAnomaliaIdRoute
  GestaoVisualizarChecklistIdRoute: typeof GestaoVisualizarChecklistIdRoute
  GestaoVisualizarDiaFolhaKeyRoute: typeof GestaoVisualizarDiaFolhaKeyRoute
  ManutencaoVisualizarAnomaliaIdRoute: typeof ManutencaoVisualizarAnomaliaIdRoute
  OperadorVisualizarAnomaliaIdRoute: typeof OperadorVisualizarAnomaliaIdRoute
  OperadorVisualizarChecklistIdRoute: typeof OperadorVisualizarChecklistIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/': {
      id: '/operador/'
      path: '/operador'
      fullPath: '/operador/'
      preLoaderRoute: typeof OperadorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao/': {
      id: '/manutencao/'
      path: '/manutencao'
      fullPath: '/manutencao/'
      preLoaderRoute: typeof ManutencaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/': {
      id: '/gestao/'
      path: '/gestao'
      fullPath: '/gestao/'
      preLoaderRoute: typeof GestaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/verso': {
      id: '/operador/verso'
      path: '/operador/verso'
      fullPath: '/operador/verso'
      preLoaderRoute: typeof OperadorVersoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/resumo': {
      id: '/operador/resumo'
      path: '/operador/resumo'
      fullPath: '/operador/resumo'
      preLoaderRoute: typeof OperadorResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/momento': {
      id: '/operador/momento'
      path: '/operador/momento'
      fullPath: '/operador/momento'
      preLoaderRoute: typeof OperadorMomentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/it': {
      id: '/operador/it'
      path: '/operador/it'
      fullPath: '/operador/it'
      preLoaderRoute: typeof OperadorItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/historico': {
      id: '/operador/historico'
      path: '/operador/historico'
      fullPath: '/operador/historico'
      preLoaderRoute: typeof OperadorHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/contexto': {
      id: '/operador/contexto'
      path: '/operador/contexto'
      fullPath: '/operador/contexto'
      preLoaderRoute: typeof OperadorContextoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/confirmacao': {
      id: '/operador/confirmacao'
      path: '/operador/confirmacao'
      fullPath: '/operador/confirmacao'
      preLoaderRoute: typeof OperadorConfirmacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/checklist': {
      id: '/operador/checklist'
      path: '/operador/checklist'
      fullPath: '/operador/checklist'
      preLoaderRoute: typeof OperadorChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao/filtros': {
      id: '/manutencao/filtros'
      path: '/manutencao/filtros'
      fullPath: '/manutencao/filtros'
      preLoaderRoute: typeof ManutencaoFiltrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao/anomalias': {
      id: '/manutencao/anomalias'
      path: '/manutencao/anomalias'
      fullPath: '/manutencao/anomalias'
      preLoaderRoute: typeof ManutencaoAnomaliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/relatorio': {
      id: '/gestao/relatorio'
      path: '/gestao/relatorio'
      fullPath: '/gestao/relatorio'
      preLoaderRoute: typeof GestaoRelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/it-treinamentos': {
      id: '/gestao/it-treinamentos'
      path: '/gestao/it-treinamentos'
      fullPath: '/gestao/it-treinamentos'
      preLoaderRoute: typeof GestaoItTreinamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/it-analytics': {
      id: '/gestao/it-analytics'
      path: '/gestao/it-analytics'
      fullPath: '/gestao/it-analytics'
      preLoaderRoute: typeof GestaoItAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/filtros': {
      id: '/gestao/filtros'
      path: '/gestao/filtros'
      fullPath: '/gestao/filtros'
      preLoaderRoute: typeof GestaoFiltrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/checklists': {
      id: '/gestao/checklists'
      path: '/gestao/checklists'
      fullPath: '/gestao/checklists'
      preLoaderRoute: typeof GestaoChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/anomalias': {
      id: '/gestao/anomalias'
      path: '/gestao/anomalias'
      fullPath: '/gestao/anomalias'
      preLoaderRoute: typeof GestaoAnomaliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/verso/ptp': {
      id: '/operador/verso/ptp'
      path: '/ptp'
      fullPath: '/operador/verso/ptp'
      preLoaderRoute: typeof OperadorVersoPtpRouteImport
      parentRoute: typeof OperadorVersoRoute
    }
    '/operador/verso/limpeza': {
      id: '/operador/verso/limpeza'
      path: '/limpeza'
      fullPath: '/operador/verso/limpeza'
      preLoaderRoute: typeof OperadorVersoLimpezaRouteImport
      parentRoute: typeof OperadorVersoRoute
    }
    '/operador/it/ata': {
      id: '/operador/it/ata'
      path: '/ata'
      fullPath: '/operador/it/ata'
      preLoaderRoute: typeof OperadorItAtaRouteImport
      parentRoute: typeof OperadorItRoute
    }
    '/operador/it/$doc': {
      id: '/operador/it/$doc'
      path: '/$doc'
      fullPath: '/operador/it/$doc'
      preLoaderRoute: typeof OperadorItDocRouteImport
      parentRoute: typeof OperadorItRoute
    }
    '/operador/anomalia/nova': {
      id: '/operador/anomalia/nova'
      path: '/operador/anomalia/nova'
      fullPath: '/operador/anomalia/nova'
      preLoaderRoute: typeof OperadorAnomaliaNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao/anomalia/nova': {
      id: '/manutencao/anomalia/nova'
      path: '/manutencao/anomalia/nova'
      fullPath: '/manutencao/anomalia/nova'
      preLoaderRoute: typeof ManutencaoAnomaliaNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/visualizar/checklist/$id': {
      id: '/operador/visualizar/checklist/$id'
      path: '/operador/visualizar/checklist/$id'
      fullPath: '/operador/visualizar/checklist/$id'
      preLoaderRoute: typeof OperadorVisualizarChecklistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/visualizar/anomalia/$id': {
      id: '/operador/visualizar/anomalia/$id'
      path: '/operador/visualizar/anomalia/$id'
      fullPath: '/operador/visualizar/anomalia/$id'
      preLoaderRoute: typeof OperadorVisualizarAnomaliaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/verso/ptp/$janelaCodigo': {
      id: '/operador/verso/ptp/$janelaCodigo'
      path: '/$janelaCodigo'
      fullPath: '/operador/verso/ptp/$janelaCodigo'
      preLoaderRoute: typeof OperadorVersoPtpJanelaCodigoRouteImport
      parentRoute: typeof OperadorVersoPtpRoute
    }
    '/manutencao/visualizar/anomalia/$id': {
      id: '/manutencao/visualizar/anomalia/$id'
      path: '/manutencao/visualizar/anomalia/$id'
      fullPath: '/manutencao/visualizar/anomalia/$id'
      preLoaderRoute: typeof ManutencaoVisualizarAnomaliaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/visualizar/dia/$folhaKey': {
      id: '/gestao/visualizar/dia/$folhaKey'
      path: '/gestao/visualizar/dia/$folhaKey'
      fullPath: '/gestao/visualizar/dia/$folhaKey'
      preLoaderRoute: typeof GestaoVisualizarDiaFolhaKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/visualizar/checklist/$id': {
      id: '/gestao/visualizar/checklist/$id'
      path: '/gestao/visualizar/checklist/$id'
      fullPath: '/gestao/visualizar/checklist/$id'
      preLoaderRoute: typeof GestaoVisualizarChecklistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/visualizar/anomalia/$id': {
      id: '/gestao/visualizar/anomalia/$id'
      path: '/gestao/visualizar/anomalia/$id'
      fullPath: '/gestao/visualizar/anomalia/$id'
      preLoaderRoute: typeof GestaoVisualizarAnomaliaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OperadorItRouteChildren {
  OperadorItDocRoute: typeof OperadorItDocRoute
  OperadorItAtaRoute: typeof OperadorItAtaRoute
}

const OperadorItRouteChildren: OperadorItRouteChildren = {
  OperadorItDocRoute: OperadorItDocRoute,
  OperadorItAtaRoute: OperadorItAtaRoute,
}

const OperadorItRouteWithChildren = OperadorItRoute._addFileChildren(
  OperadorItRouteChildren,
)

interface OperadorVersoPtpRouteChildren {
  OperadorVersoPtpJanelaCodigoRoute: typeof OperadorVersoPtpJanelaCodigoRoute
}

const OperadorVersoPtpRouteChildren: OperadorVersoPtpRouteChildren = {
  OperadorVersoPtpJanelaCodigoRoute: OperadorVersoPtpJanelaCodigoRoute,
}

const OperadorVersoPtpRouteWithChildren =
  OperadorVersoPtpRoute._addFileChildren(OperadorVersoPtpRouteChildren)

interface OperadorVersoRouteChildren {
  OperadorVersoLimpezaRoute: typeof OperadorVersoLimpezaRoute
  OperadorVersoPtpRoute: typeof OperadorVersoPtpRouteWithChildren
}

const OperadorVersoRouteChildren: OperadorVersoRouteChildren = {
  OperadorVersoLimpezaRoute: OperadorVersoLimpezaRoute,
  OperadorVersoPtpRoute: OperadorVersoPtpRouteWithChildren,
}

const OperadorVersoRouteWithChildren = OperadorVersoRoute._addFileChildren(
  OperadorVersoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GestaoAnomaliasRoute: GestaoAnomaliasRoute,
  GestaoChecklistsRoute: GestaoChecklistsRoute,
  GestaoFiltrosRoute: GestaoFiltrosRoute,
  GestaoItAnalyticsRoute: GestaoItAnalyticsRoute,
  GestaoItTreinamentosRoute: GestaoItTreinamentosRoute,
  GestaoRelatorioRoute: GestaoRelatorioRoute,
  ManutencaoAnomaliasRoute: ManutencaoAnomaliasRoute,
  ManutencaoFiltrosRoute: ManutencaoFiltrosRoute,
  OperadorChecklistRoute: OperadorChecklistRoute,
  OperadorConfirmacaoRoute: OperadorConfirmacaoRoute,
  OperadorContextoRoute: OperadorContextoRoute,
  OperadorHistoricoRoute: OperadorHistoricoRoute,
  OperadorItRoute: OperadorItRouteWithChildren,
  OperadorMomentoRoute: OperadorMomentoRoute,
  OperadorResumoRoute: OperadorResumoRoute,
  OperadorVersoRoute: OperadorVersoRouteWithChildren,
  GestaoIndexRoute: GestaoIndexRoute,
  ManutencaoIndexRoute: ManutencaoIndexRoute,
  OperadorIndexRoute: OperadorIndexRoute,
  ManutencaoAnomaliaNovaRoute: ManutencaoAnomaliaNovaRoute,
  OperadorAnomaliaNovaRoute: OperadorAnomaliaNovaRoute,
  GestaoVisualizarAnomaliaIdRoute: GestaoVisualizarAnomaliaIdRoute,
  GestaoVisualizarChecklistIdRoute: GestaoVisualizarChecklistIdRoute,
  GestaoVisualizarDiaFolhaKeyRoute: GestaoVisualizarDiaFolhaKeyRoute,
  ManutencaoVisualizarAnomaliaIdRoute: ManutencaoVisualizarAnomaliaIdRoute,
  OperadorVisualizarAnomaliaIdRoute: OperadorVisualizarAnomaliaIdRoute,
  OperadorVisualizarChecklistIdRoute: OperadorVisualizarChecklistIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
